# Generated by Django 5.2.7 on 2026-01-21 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('direction', 'Direction'), ('chef', 'Chef de service'), ('collaborateur', 'Collaborateur'), ('agent_courrier', 'Agent courrier'), ('archiviste', 'Archiviste'), ('agent_service', 'Agent de service')], default='collaborateur', max_length=30),
        ),
    ]
