# Generated by Django 5.2.7 on 2026-01-18 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courriers', '0006_courrier_expediteur_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='courrier',
            name='exte_extrait_path',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Chemin du fichier texte extrait'),
        ),
        migrations.AddField(
            model_name='courrier',
            name='texte_extrait_path',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Chemin du fichier texte extrait'),
        ),
        migrations.AlterField(
            model_name='courrier',
            name='canal',
            field=models.CharField(choices=[('physique', 'Physique'), ('email', 'Email'), ('portail', 'Portail'), ('telephone', 'Téléphone'), ('autre', 'Autre')], default='physique', max_length=20),
        ),
    ]
