# Generated by Django 5.2.7 on 2026-01-21 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courriers', '0007_courrier_exte_extrait_path_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courrier',
            name='texte_extrait_path',
        ),
    ]
