# Generated by Django 5.2.7 on 2026-02-09 05:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
        ('courriers', '0008_remove_courrier_texte_extrait_path'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='courrier',
            name='agent_traitant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courriers_traitant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='courrier',
            name='besoin_validation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='courrier',
            name='date_debut_traitement',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courrier',
            name='date_fin_traitement',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courrier',
            name='delai_traitement_jours',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='courrier',
            name='niveau_validation_atteint',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='courrier',
            name='niveau_validation_requis',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='courrier',
            name='traitement_statut',
            field=models.CharField(choices=[('prise_en_charge', 'Prise en charge'), ('analyse', 'Analyse en cours'), ('instruction', 'Instruction'), ('redaction', 'Rédaction réponse'), ('validation', 'En validation'), ('signature', 'À signature'), ('envoi', 'À envoyer'), ('cloture', 'Clôturé'), ('rejete', 'Rejeté')], default='prise_en_charge', max_length=20),
        ),
        migrations.CreateModel(
            name='CourrierReponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_reponse', models.CharField(choices=[('lettre', 'Lettre officielle'), ('email', 'Email'), ('note_interne', 'Note interne'), ('decision', 'Décision'), ('avis_technique', 'Avis technique'), ('accuse_reception', 'Accusé de réception')], default='lettre', max_length=50)),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('objet', models.CharField(max_length=500)),
                ('contenu', models.TextField()),
                ('destinataires', models.JSONField()),
                ('copies', models.JSONField(blank=True, default=list)),
                ('date_redaction', models.DateTimeField(auto_now_add=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('date_signature', models.DateTimeField(blank=True, null=True)),
                ('date_envoi', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('a_valider', 'À valider'), ('a_corriger', 'À corriger'), ('a_signature', 'À signature'), ('a_envoyer', 'À envoyer'), ('envoye', 'Envoyé'), ('archive', 'Archivé')], default='brouillon', max_length=20)),
                ('pieces_jointes_reponse', models.JSONField(blank=True, default=list)),
                ('canal_envoi', models.CharField(choices=[('email', 'Email'), ('courrier', 'Courrier physique'), ('portail', 'Portail web'), ('fax', 'Fax'), ('messagerie', 'Messagerie interne')], default='email', max_length=50)),
                ('confirmation_reception', models.BooleanField(default=False)),
                ('date_confirmation', models.DateTimeField(blank=True, null=True)),
                ('template_html', models.TextField(blank=True, null=True)),
                ('entete', models.TextField(blank=True, null=True)),
                ('pied_page', models.TextField(blank=True, null=True)),
                ('signature_html', models.TextField(blank=True, null=True)),
                ('courrier_origine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='courriers.courrier')),
                ('modele_utilise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courriers.modelecourrier')),
                ('redacteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reponses_redigees', to=settings.AUTH_USER_MODEL)),
                ('signataire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reponses_signees', to=settings.AUTH_USER_MODEL)),
                ('validateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reponses_validees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Réponse de courrier',
                'verbose_name_plural': 'Réponses de courrier',
                'db_table': 'courrier_reponse',
                'ordering': ['-date_redaction'],
            },
        ),
        migrations.AddField(
            model_name='courrier',
            name='reponse_associee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courrier_source', to='courriers.courrierreponse'),
        ),
        migrations.CreateModel(
            name='InstructionCourrier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_instruction', models.CharField(choices=[('analyse', 'Analyse préliminaire'), ('recherche', "Recherche d'informations"), ('consultation', "Consultation d'expert"), ('verification', 'Vérification réglementaire'), ('calcul', 'Calculs nécessaires'), ('recommandation', 'Recommandation')], max_length=50)),
                ('instruction', models.TextField()),
                ('date_assignation', models.DateTimeField(auto_now_add=True)),
                ('date_echeance', models.DateTimeField(blank=True, null=True)),
                ('date_accomplie', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours'), ('termine', 'Terminé'), ('reporte', 'Reporté'), ('annule', 'Annulé')], default='en_attente', max_length=20)),
                ('resultat', models.TextField(blank=True, null=True)),
                ('documents_produits', models.JSONField(blank=True, default=list)),
                ('agent_assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instructions_assignees', to=settings.AUTH_USER_MODEL)),
                ('courrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructions', to='courriers.courrier')),
            ],
            options={
                'verbose_name': 'Instruction de traitement',
                'verbose_name_plural': 'Instructions de traitement',
                'db_table': 'courrier_instruction',
                'ordering': ['date_assignation'],
            },
        ),
        migrations.CreateModel(
            name='TraitementEtape',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_etape', models.CharField(choices=[('prise_en_charge', 'Prise en charge'), ('lecture', 'Lecture et analyse'), ('instruction', 'Instruction du dossier'), ('redaction', 'Rédaction de la réponse'), ('avis', 'Avis technique'), ('validation', 'Validation hiérarchique'), ('signature', 'Signature'), ('envoi', 'Envoi/Réponse'), ('cloture', 'Clôture'), ('rejet', 'Rejet'), ('transfert', 'Transfert à un autre service')], max_length=50)),
                ('description', models.TextField()),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('date_debut', models.DateTimeField(auto_now_add=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('duree_minutes', models.IntegerField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('termine', 'Terminé'), ('en_attente', 'En attente'), ('bloque', 'Bloqué'), ('annule', 'Annulé')], default='en_cours', max_length=20)),
                ('documents_associes', models.JSONField(blank=True, default=list)),
                ('validation_requise', models.BooleanField(default=False)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('courrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traitement_etapes', to='courriers.courrier')),
                ('validateurs', models.ManyToManyField(blank=True, related_name='validations_a_realiser', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Étape de traitement',
                'verbose_name_plural': 'Étapes de traitement',
                'db_table': 'courrier_traitement_etape',
                'ordering': ['date_debut'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowValidation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('type_courrier', models.CharField(choices=[('entrant', 'Courrier entrant'), ('sortant', 'Courrier sortant'), ('interne', 'Courrier interne')], max_length=20)),
                ('etapes_validation', models.JSONField()),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('category_associee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.category')),
                ('service_associe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.service')),
            ],
            options={
                'verbose_name': 'Workflow de validation',
                'verbose_name_plural': 'Workflows de validation',
                'db_table': 'courrier_workflow_validation',
                'unique_together': {('nom', 'type_courrier', 'service_associe')},
            },
        ),
        migrations.AddField(
            model_name='courrier',
            name='workflow_validation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courriers.workflowvalidation'),
        ),
        migrations.CreateModel(
            name='ValidationCourrier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_validation', models.CharField(choices=[('technique', 'Validation technique'), ('hierarchique', 'Validation hiérarchique'), ('juridique', 'Validation juridique'), ('financiere', 'Validation financière'), ('signature', 'Signature')], max_length=50)),
                ('ordre', models.IntegerField(default=1)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('valide', 'Validé'), ('rejete', 'Rejeté'), ('modification', 'Modifications requises'), ('signe', 'Signé')], default='en_attente', max_length=20)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('date_action', models.DateTimeField(blank=True, null=True)),
                ('signature_data', models.JSONField(blank=True, null=True)),
                ('signature_image', models.TextField(blank=True, null=True)),
                ('certificat_info', models.JSONField(blank=True, null=True)),
                ('courrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validations', to='courriers.courrier')),
                ('validateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Validation de courrier',
                'verbose_name_plural': 'Validations de courrier',
                'db_table': 'courrier_validation',
                'ordering': ['ordre', 'date_demande'],
                'unique_together': {('courrier', 'ordre')},
            },
        ),
    ]
