# Generated by Django 5.2.7 on 2026-02-12 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courriers', '0009_courrier_agent_traitant_courrier_besoin_validation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courrier',
            name='analyse_ia',
            field=models.TextField(blank=True, null=True),
        ),
    ]
