# Generated by Django 5.2.7 on 2026-02-16 09:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courriers', '0010_courrier_analyse_ia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='courrier',
            name='actions_requises',
            field=models.JSONField(blank=True, default=list, verbose_name='Actions requises'),
        ),
        migrations.AddField(
            model_name='courrier',
            name='analyse_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date d'analyse"),
        ),
        migrations.AddField(
            model_name='courrier',
            name='analyse_notes',
            field=models.TextField(blank=True, null=True, verbose_name="Notes d'analyse"),
        ),
        migrations.AddField(
            model_name='courrier',
            name='analyse_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courriers_analyses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='courrier',
            name='consultations',
            field=models.JSONField(blank=True, default=list, verbose_name='Consultations externes'),
        ),
        migrations.AddField(
            model_name='courrier',
            name='decision_preliminaire',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courrier',
            name='documents_necessaires',
            field=models.JSONField(blank=True, default=list, verbose_name='Documents nécessaires'),
        ),
    ]
