# Generated by Django 5.2.7 on 2026-03-19 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courriers', '0011_courrier_actions_requises_courrier_analyse_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courrier',
            name='reference_expediteur',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Référence du courrier de départ'),
        ),
    ]
