# Generated by Django 5.2.7 on 2026-03-16 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0002_workflowstep_actions_requises_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowtemplate',
            name='steps_config',
            field=models.JSONField(blank=True, default=list, help_text="Config des étapes : [{'label': 'Validation chef', 'role': 'chef', 'actions': ['valider']}, ...]"),
        ),
    ]
